(part "CSD18542KCS"
    (packageRef "TO254P470X1016X2016-3P")
    (interface
        (port "1" (symbPinId 1) (portName "G") (portType INOUT))
        (port "2" (symbPinId 2) (portName "D") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "595-CSD18542KCS")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/CSD18542KCS?qs=sICFeol8QWE7Rbjncdrc5g%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "CSD18542KCS")
    (property "Description" "CSD18542KCS 60-V N-Channel NexFET&#153; Power MOSFET")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/csd18542kcs")
    (property "symbolName1" "CSD18542KCS")
)
