(part "LDL1117S33R"
    (packageRef "SOT230P700X180-4N")
    (interface
        (port "1" (symbPinId 1) (portName "GND") (portType GROUND))
        (port "2" (symbPinId 2) (portName "VOUT_1") (portType OUTPUT))
        (port "3" (symbPinId 3) (portName "VIN") (portType INPUT))
        (port "4" (symbPinId 4) (portName "VOUT_2") (portType OUTPUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "511-LDL1117S33R")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/LDL1117S33R?qs=AQlKX63v8Rt9Bf6AWSrbFg%3D%3D")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "LDL1117S33R")
    (property "Description" "STMICROELECTRONICS - LDL1117S33R - LDO, FIXED, 3.3V, 1.2A, SOT-223-3")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/ldl1117.pdf")
    (property "symbolName1" "LDL1117S33R")
)
