(part "SMC30J18A"
    (packageRef "DIOM8059X265N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "SMC30J18A")
    (property "Description" "3000 W,18 V TVS in SMC")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/smc30j10a.pdf")
    (property "symbolName1" "SMC30J18A")
)
